### ISSUE TITLE
Shall we allow adding disjunctive condition to reachabilityMap in addReachabilityMapping?

### ISSUE THREAD

**Issue by RabbitWhite1** [fruffy/flay#58]
In current implementation of `addReachabilityMapping`, we always try to initialize for a pair of `node` and `cond`. However, in cases like this:
```p4
action copy_to_cpu(...) {
    // An if statement
    if (some_cond) {
        x = a;
    } else {
        x = b;
    }
    // codes to copy to cpu
}

action redirect_to_cpu(...) {
    // codes to drop
    copy_to_cpu(...) // this calls the previous action
}
```
the if statement in `copy_to_cpu` will be visited twice. And our `ReachabilityMap` is compared by `SourceIdCmp`. Thus, the second time to call `addReachabilityMapping` for this if statement will failed [here](https://github.com/fruffy/flay/blob/d8fba04c7fcb39a802e1992fef972e1fb2cf4c4a/core/execution_state.cpp#L137).

I encountered this issue when trying on Tofino's switch program. And my fix in mind is instead of asserting existence of `node`, we should add new condition as disjunction to the `reachabilityMap`.

**Comment by RabbitWhite1** [comment]
> What do you mean exactly with disjunction here?

 For dead code elimination, we want to know if some codes will never be reached. Let's say the condition of an `ifTrue` branch is `cond1` when the stack is [call action1], and `cond2` when the stack is [call action2, call action1]. Then the reachability of the `ifTrue1` branch should be `cond1 or cond2`. Thus we can update the reachability map, e.g. from `ifstatement->cond1` to `ifstatement->(cond1 or cond2)`. 

> One way to approach this problem is to make the source info mapping a stack.

I think this is a good solution. But I am also not sure what data structure works best.

**Comment by fruffy** [comment]
> For dead code elimination, we want to know if some codes will never be reached. Let's say the condition of an `ifTrue` branch is `cond1` when the stack is [call action1], and `cond2` when the stack is [call action2, call action1]. Then the reachability of the `ifTrue` branch should be `cond1 or cond2`. Thus we can update the reachability map, e.g. from `ifstatement->cond1` to `ifstatement->(cond1 or cond2)`.

Ah I see what you mean. I think this can work and might be easier than my approach. But it may not account for inlining of these calls. If one call is always dead and the other one always active, both will be considered alive even though we could remove one.

**Comment by RabbitWhite1** [comment]
Yes, the inlining is indeed a problem. What would you suggest to do as a workaround so that I can continue working on the Tofino switch program?

**Comment by fruffy** [comment]
Let's go with your disjunctive approach first. Instead of a map of nodes it will be a map of node vectors?

The unique source info approach requires more work because we will have to design a key for a vector of source infos.

**Comment by RabbitWhite1** [comment]
Sounds good.

>  Instead of a map of nodes it will be a map of node vectors?
I think the original `std::map<const IR::Node *, ReachabilityExpression, SourceIdCmp>` shall be fine, because different nodes with same sourceInfo will find the same `ReachabilityExpression`. Did I miss something?

**Comment by fruffy** [comment]
Oh sorry for the confusion, I mean a vector for `ReachabilityExpression`

**Comment by RabbitWhite1** [comment]
Ah I see. Yes, we can use a vector for `ReachabilityExpression`.

**Comment by RabbitWhite1** [comment]
On second thought, what about just changing the ReachabilityExpression to an or-ed result when adding? This can somewhat minimize changes to the code.

**Comment by fruffy** [comment]
I would keep each ReachabilityExpression independent and just OR the results of the vector when computing a condition.
